name: skintelligent
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment: 
  sdk: ^3.5.3

dependencies:
  animated_text_kit: ^4.2.2
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  flutter_otp_text_field: ^1.4.0+2
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^4.0.0
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  hive: ^2.2.3
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  mobile_scanner: ^6.0.6
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
